spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: qwer1234.333
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: demo
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  config: classpath:logback-spring.xml
  file:
    path: /home/ubuntu/BlogLogs/

server:
  port: 80


upload:
  file:
    path: /home/ubuntu/Upload/